### ISSUE TITLE
White triangles on fire/infernal cape

### ISSUE THREAD

**Issue by aekramer** [Elvarg-Community/Elvarg-Client-Public#12]
White triangles seem to appear on the back/shoulder part of the player model for textured capes (other textured items appear to be fine)

Picture for reference (shot from the side as this is the easiest way to spot it, the players left side has a smaller portion sticking out)

![image](https://user-images.githubusercontent.com/15050467/194961065-12b98bf8-7364-4d51-b65b-469a94a8eebc.png)

**Comment by Mark7625** [comment]
This has been fixed
