### ISSUE TITLE
Bugs for RuneLite Client

### ISSUE THREAD

**Issue by NataIynn** [Elvarg-Community/Elvarg-Client-Public#6]
**Here's some bugs I've found:**
- Shadows doesn't render unless, render distance is around 90.
- Unlock FPS doesn't work on 117 HD. 
- Game Rendering seems to break when disabling 117 HD.
- Resizable Screen (Chat Box) set to transparent is black.
- Interface Tabs Overlapping in fixed mode.
- Overhead Chat Messages isn't aligned properly.

**Not sure if this is client issue or server.**
- When walking around, character seems to freeze up, along with every interaction with the client.

![image](https://user-images.githubusercontent.com/28743579/175302898-a20a6fea-5308-4b4c-80f0-b1e7d2185ce8.png)

**Comment by Mark7625** [comment]
Shadows doesn't render unless, render distance is around 90.
Game Rendering seems to break when disabling 117 HD
Resizable Screen (Chat Box) set to transparent is black.
 These should be fixed now lmk

**Comment by NataIynn** [comment]
Chatbox is still black on resizable, shadows still seem broken.
![image](https://user-images.githubusercontent.com/28743579/177678774-9eaa17ec-18be-4513-a9b0-91470d881540.png)

Textures at GE floor is broken & objects missing.
![image](https://user-images.githubusercontent.com/28743579/177678857-865d4528-4705-4834-8b1d-94891c359ea7.png)

Ditch seems broken like the GE floor tiles.
![image](https://user-images.githubusercontent.com/28743579/177678926-b5212cb5-5a37-4768-9610-c9b6d54a253b.png)

Also the unlocked fps still seems broken, and doesn't get unlocked while the GPU plugin works fine.
